### ISSUE TITLE
微信的斗图代码更新了

### ISSUE THREAD

**Issue by OuO-dodo** [QiaoJianCheng/Gifin#6]
![IMG_20230609_010114](https://github.com/jianchengqiao/Gifin/assets/95514064/72f1754a-e52b-4402-8e91-70cbdfb115a4)
现在搜狗输入法的斗图代码已经变为content://开头，向请教一下作者能不能看出其中原理

**Comment by jianchengqiao** [comment]
> 

这个显然不是用文件路径了，用的是资源 uri，Android 里面有 ContentProvider 和 ContentResolver 可以处理，我已经很久没做过 Android 了，网上查查应该很容易找到

**Comment by OuO-dodo** [comment]
好的，感谢解答
